const ReviewData = [
    {
        id: 1,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 2,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 3,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 4,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 5,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 6,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 7,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 8,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 9,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 10,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 1,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 2,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 3,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 4,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 5,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 6,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 7,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 8,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 9,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 10,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 1,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 2,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 3,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 4,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 5,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 6,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 7,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 8,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 9,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 10,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 1,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 2,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 3,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 4,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 5,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 6,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 7,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 8,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 9,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 10,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 1,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 2,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 3,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 4,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 5,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 6,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 7,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 8,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 9,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 10,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 1,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 2,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 3,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 4,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 5,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 6,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 7,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 8,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 9,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
    {
        id: 10,
        name:'Rimi Chowdhury',
        rating: 5,
        comment: 'Very cute plush! Good quality',
    },
]